/**
 * This file generates pkg/rancher-desktop/assets/extension-data.yaml
 *
 * Usage: `yarn generate:extension-data`
 */

import fs from 'fs';

import yaml from 'yaml';

import { getExtensions } from './lib/extension-data';

const warningString =
  '# Data generated by running `yarn generate:extension-data`. DO NOT EDIT.';

async function run() {
  const fileName = 'pkg/rancher-desktop/assets/extension-data.yaml';
  const extensions = getExtensions();
  const promises = extensions.map(e => e.generateMarketplaceData());
  const data = await Promise.all(promises);
  const result = `${ warningString }\n${ yaml.stringify(data) }`;

  await fs.promises.writeFile(fileName, result, 'utf-8');
}

run().catch((ex) => {
  console.error(ex);
  process.exit(1);
});
