name: BATS with OpenVPN
on:
  workflow_dispatch: {}
  push:
    branches: [ ci/vpn ]
permissions:
  contents: read

jobs:
  generate-config:
    name: Generate OpenVPN Configuration
    runs-on: ubuntu-latest
    container: registry.opensuse.org/opensuse/leap:15.6
    steps:
    - name: Write helper to output file to step output
      shell: cp {0} output-file
      run: |
        #!/bin/sh
        # This script emits output variable {1} using the contents of {2}
        # with delimiter {3}
        set -o errexit -o nounset
        output_var=$1
        input_file=$2
        delimiter=${3:-$(openssl rand -base64 48)}
        >> "$GITHUB_OUTPUT" echo "${output_var}<<${delimiter}"
        >> "$GITHUB_OUTPUT" cat "$input_file"
        >> "$GITHUB_OUTPUT" echo "${delimiter}"
    - name: Write helper to embed file into OpenVPN configuration
      shell: cp {0} embed-file
      run: |
        #!/usr/bin/bash
        # This script embeds the file "$2" using the tag "$1" into file "$3"
        set -o errexit -o nounset
        printf '<%s>\n' "$1" >> "$3"
        cat "$2" >> "$3"
        printf '</%s>\n' "$1" >> "$3"
    - name: Generate keys
      run: |
        chmod a+x output-file embed-file
        zypper --non-interactive install easy-rsa openvpn
        easyrsa init-pki

        cat >pki/vars <<EOF
        set_var EASYRSA_DN             cn_only
        set_var EASYRSA_NO_PASS        1
        set_var EASYRSA_ALGO           ed
        set_var	EASYRSA_DISABLE_INLINE 0
        set_var EASYRSA_BATCH          1
        EOF

        easyrsa build-ca
        easyrsa gen-req server
        easyrsa sign-req client server
        easyrsa gen-crl
        openvpn --genkey secret pki/ta.key
        easyrsa gen-req client
        easyrsa sign-req client client
    - name: Write server.conf
      run: |
        cat >server.conf <<EOF
        port 1194
        proto tcp
        dev tun
        topology subnet
        server 10.8.0.0 255.255.255.0
        ifconfig-pool-persist ipp.txt
        keepalive 10 3600
        key-direction 0
        cipher AES-256-GCM
        dh none
        compress lz4-v2
        push "compress lz4-v2"
        persist-key
        persist-tun
        verb 5
        mute 20
        explicit-exit-notify 1
        EOF
        ./embed-file ca pki/ca.crt server.conf
        ./embed-file cert pki/issued/server.crt server.conf
        ./embed-file key pki/private/server.key server.conf
        ./embed-file tls-auth pki/ta.key server.conf
        ./output-file server.conf server.conf
    - name: Write client.conf
      run: |
        cat >client.conf <<EOF
        cipher AES-256-GCM
        dev tun
        key-direction 1
        topology subnet
        remote 127.0.0.1
        proto tcp
        port 1194
        nobind
        remote-cert-tls server
        tls-client
        allow-compression yes
        pull
        EOF
        ./embed-file ca pki/ca.crt client.conf
        ./embed-file cert pki/issued/client.crt client.conf
        ./embed-file key pki/private/client.key client.conf
        ./embed-file tls-auth pki/ta.key client.conf
        ./output-file client.conf client.conf
  run-linux:
    needs: generate-config
    runs-on: ubuntu-latest
    services:
      server:
        image: registry.opensuse.org/opensuse/leap:15.6
        ports: [ 1194 ]
    steps:
    - run: |
        true
