name: Screenshots

on:
  workflow_dispatch:
    inputs:
      mock_version:
        description: Mock Version
        type: string
        required: true
        default: '1.0.0'

jobs:
  screenshot:
    name: Take screenshot
    strategy:
      matrix:
        include:
        - platform: mac
          runs-on: macos-11
        - platform: win
          runs-on: windows-2019
        - platform: linux
          runs-on: ubuntu-22.04
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-node@v4
      with:
        node-version: '18.16.x'
        cache: yarn
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.21'
        cache-dependency-path: src/go/**/go.sum
    - name: Install Windows dependencies
      if: runner.os == 'Windows'
      shell: powershell
      run: .\scripts\windows-setup.ps1 -SkipVisualStudio -SkipTools
    - name: Install ShareX
      if: runner.os == 'Windows'
      run: |
        New-Item -Force -ItemType Directory resources/ShareX
        Invoke-WebRequest -UseBasicParsing -OutFile sharex.zip `
          https://github.com/ShareX/ShareX/releases/download/v15.0.0/ShareX-15.0.0-portable.zip
        Expand-Archive sharex.zip resources/ShareX
    - name: Install gnome-screenshot
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install gnome-screenshot
    - name: Install GetWindowID
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install smokris/getwindowid/getwindowid
    - run: pip install setuptools
    - # Needs a network timeout for macos & windows. See https://github.com/yarnpkg/yarn/issues/8242 for more info
      run: yarn install --frozen-lockfile --network-timeout 1000000
    - name: Override version
      if: inputs.mock_version
      run: echo "RD_MOCK_VERSION=${{ inputs.mock_version }}" >> "${GITHUB_ENV}"
      shell: bash
    - run: yarn screenshots
      env:
        RD_ENV_SCREENSHOT_SLEEP: 5000
        RD_DEBUG_ENABLED: '1'
        RD_LOGS_DIR: logs
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots-${{ matrix.platform }}.zip
        path: ./screenshots/output/*
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: logs-${{ matrix.platform }}.zip
        path: ./logs/*
