name: Check Spelling

on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "**"
  pull_request_target:
    branches:
    - "**"
    types:
    - 'opened'
    - 'reopened'
    - 'synchronize'

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
      security-events: write # To be able to write SARIF events
    runs-on: ubuntu-latest
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - uses: ./.github/actions/yarn-install
    - uses: ./.github/actions/setup-environment
    - run: sudo apt-get install cpanminus

    - name: Check Spelling
      run: yarn lint:spelling
      env:
        GITHUB_TOKEN: ${{ github.token }} # for SARIF uploading
