name: e2e tests on Windows

on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'dependabot/**'
  pull_request: {}

defaults:
  run:
    shell: powershell
jobs:
  check-paths:
    uses: ./.github/workflows/paths-ignore.yaml
  e2e-tests:
    needs: check-paths
    if: needs.check-paths.outputs.should-run == 'true'
    timeout-minutes: 90
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-environment
      # For compatibility with runners without yarn, we need to install node
      # once, install yarn, then install node again to get caching.
      - uses: actions/setup-node@v4
        with:
          node-version: '18.16.x'
      - run: corepack enable yarn
      - uses: actions/setup-node@v4
        with:
          node-version: '18.16.x'
          cache: yarn
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21'
          cache: 'true'
          cache-dependency-path: src/go/**/go.sum
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install setuptools
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run e2e Tests
        run: yarn test:e2e
        env:
          RD_DEBUG_ENABLED: '1'
      - name: Upload failure reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2etest-artifacts
          path: ./e2e/reports/*
