# This is a temporary workflow to build Windows Installer packages before it is
# completely integrated.
name: Windows Installer

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  package:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        # Needed to run `git describe` to get full version info
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - uses: actions/setup-python@v4
      with:
        python-version: '2.x'
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18'
    - name: Install Windows dependencies
      shell: powershell
      run: .\scripts\windows-setup.ps1 -SkipVisualStudio -SkipTools
    - run: npm ci
    - run: npm run build -- --win --publish=never
    - run: npm run wix
    - name: Upload Windows installer
      uses: actions/upload-artifact@v3
      with:
        name: Rancher Desktop Setup.msi
        path: dist/Rancher Desktop*.msi
        if-no-files-found: error
